# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd5bad85ad477b8cbb9036bd6d7da30d"
name = "Bundles Adsgun"
handle = "bundles-adsgun"
application_url = "https://christmas-nz-experiment-lawn.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,read_products,write_cart_transforms,write_products,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
  "https://christmas-nz-experiment-lawn.trycloudflare.com/auth/callback",
  "https://christmas-nz-experiment-lawn.trycloudflare.com/auth/shopify/callback",
  "https://christmas-nz-experiment-lawn.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
